name: sweetalertv2
description: Sweet alert v2 for flutter.
version: 0.0.1
author: Bruno Minervino <brnminervino@gmail.com>
homepage: https://github.com/brunominervino/sweetalertv2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sequence_animation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
